---
title: "Introducción a R"
output: html_notebook
---

## Motivación

* Diaramente se almacenan masivamente grandes colecciones de datos.
* Ej: La Web, comercio electrónico, datos transaccionales.
* Los computadores se vuelven cada vez más baratos y con mayor poder de procesamiento.
* Analizar estos datos permite encontrar patrones ocultos.
* Un buen uso de los datos puede traer beneficios de negocio. Ej: segmentación de clientes, predicción de demanda.


## El proyecto R para la estadı́stica computacional

* R es un ambiente de programación estadı́stico totalmente gratuito: http://www.r-project.org/
* Permite manipular y almacenar datos de manera efectiva.
* Es un lenguaje de programación completo: variables, loop, condiciones, funciones.
* Provee muchas librerías para realizar distintos tipos de análisis sobre colecciones de datos, ej: visualización de datos, análisis de series temporales, análisis de grafos, análisis de texto.
* Las librerías junto a sus dependencias se encuentra ordenadas en un repositorio llamado **CRAN**: http://cran.r-project.org/


## R puede ser usado como una calculadora

```{r}
4*5
2^3
exp(-5)
log(4)
```

